pipeline {
    agent any
    tools { 
        maven 'MAVEN_HOME' 
        jdk 'JAVA_HOME' 
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
                git branch: 'master',
                credentialsId: 'github-cred',
                url: 'https://github.com/saswati24/simple-java-maven-app.git'

                sh "ls -lat"
                sh "mvn clean package"
                sh "java -jar target/my-app-1.0-SNAPSHOT-jar-with-dependencies.jar"
                }
        }
        stage('test') {
            steps {
                echo 'testing'
            }
        }
        stage('build') {
            steps {
                echo 'building'
            }
        }
        stage('deploy') {
            steps {
                echo 'deploying'
            }
        }    
        
    }
}
